# Generated by Django 3.0 on 2023-07-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'List of Cities'},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
