# Generated by Django 3.0 on 2023-07-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuery',
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'List of Buses'},
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(default='2023-07-31'),
        ),
    ]
