# Generated by Django 3.0 on 2023-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230731_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='date_option',
            field=models.CharField(choices=[('specific', 'Specific Date'), ('daily', 'Daily')], default='specific', max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
