# Generated by Django 3.0 on 2023-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230731_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(),
        ),
    ]
